capifony:
  #build: .
  image: ypereirareis/capifony:1.0
  environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
  volumes:
      - ./:/home/capifony/project
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - ~/.ssh/id_rsa:/home/capifony/.ssh/id_rsa
      - ~/.ssh/known_hosts:/home/capifony/.ssh/known_hosts
